import com.gluonhq.charm.glisten.control.TextField;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.TableColumn;

public class PleaseProvideControllerClassName {

    @FXML
    private Button BTNDDelete;

    @FXML
    private Button BTNDLoad;

    @FXML
    private Button BTNDSave;

    @FXML
    private Button BTNDSearch;

    @FXML
    private Button BTNDUpdate;

    @FXML
    private Button BTNDeptDelete;

    @FXML
    private Button BTNDeptLoad;

    @FXML
    private Button BTNDeptSave;

    @FXML
    private Button BTNDeptSearch;

    @FXML
    private Button BTNDeptUpdate;

    @FXML
    private Button BTNSDelete;

    @FXML
    private Button BTNSLoad;

    @FXML
    private Button BTNSSave;

    @FXML
    private Button BTNSSearch;

    @FXML
    private Button BTNSTDelete;

    @FXML
    private Button BTNSTLoad;

    @FXML
    private Button BTNSTSave;

    @FXML
    private Button BTNSTSearch;

    @FXML
    private Button BTNSTUpdate;

    @FXML
    private Button BTNSUpdate;

    @FXML
    private Button BTNTDelete;

    @FXML
    private Button BTNTLoad;

    @FXML
    private Button BTNTSave;

    @FXML
    private Button BTNTSearch;

    @FXML
    private Button BTNTUpdate;

    @FXML
    private TableColumn<?, ?> ColDescription;

    @FXML
    private TableColumn<?, ?> ColID;

    @FXML
    private TableColumn<?, ?> ColSAge;

    @FXML
    private TableColumn<?, ?> ColSAge1;

    @FXML
    private TableColumn<?, ?> ColSAge2;

    @FXML
    private TableColumn<?, ?> ColSDepartment;

    @FXML
    private TableColumn<?, ?> ColSDepartment1;

    @FXML
    private TableColumn<?, ?> ColSDeptID;

    @FXML
    private TableColumn<?, ?> ColSDeptID1;

    @FXML
    private TableColumn<?, ?> ColSDeptID2;

    @FXML
    private TableColumn<?, ?> ColSDuty;

    @FXML
    private TableColumn<?, ?> ColSDuty1;

    @FXML
    private TableColumn<?, ?> ColSDuty2;

    @FXML
    private TableColumn<?, ?> ColSGender;

    @FXML
    private TableColumn<?, ?> ColSGender1;

    @FXML
    private TableColumn<?, ?> ColSGender2;

    @FXML
    private TableColumn<?, ?> ColSID;

    @FXML
    private TableColumn<?, ?> ColSID1;

    @FXML
    private TableColumn<?, ?> ColSID2;

    @FXML
    private TableColumn<?, ?> ColSName;

    @FXML
    private TableColumn<?, ?> ColSName1;

    @FXML
    private TableColumn<?, ?> ColSName2;

    @FXML
    private TableColumn<?, ?> ColSTAge;

    @FXML
    private TableColumn<?, ?> ColSTCourse;

    @FXML
    private TableColumn<?, ?> ColSTDeptID;

    @FXML
    private TableColumn<?, ?> ColSTGender;

    @FXML
    private TableColumn<?, ?> ColSTID;

    @FXML
    private TableColumn<?, ?> ColSTName;

    @FXML
    private TableColumn<?, ?> ColSWorkload;

    @FXML
    private TableColumn<?, ?> ColSWorkload1;

    @FXML
    private TableColumn<?, ?> ColSWorkload2;

    @FXML
    private Label LBLDAgw;

    @FXML
    private Label LBLDDeptID;

    @FXML
    private Label LBLDDescription;

    @FXML
    private Label LBLDDuty;

    @FXML
    private Label LBLDGender;

    @FXML
    private Label LBLDID;

    @FXML
    private Label LBLDName;

    @FXML
    private Label LBLDWorkload;

    @FXML
    private Label LBLDeptID;

    @FXML
    private Label LBLSAge;

    @FXML
    private Label LBLSDeptID;

    @FXML
    private Label LBLSDuty;

    @FXML
    private Label LBLSGender;

    @FXML
    private Label LBLSID;

    @FXML
    private Label LBLSName;

    @FXML
    private Label LBLSTAge;

    @FXML
    private Label LBLSTCourse;

    @FXML
    private Label LBLSTDeptID;

    @FXML
    private Label LBLSTGender;

    @FXML
    private Label LBLSTID;

    @FXML
    private Label LBLSTName;

    @FXML
    private Label LBLSWorkload;

    @FXML
    private Label LBLTAge;

    @FXML
    private Label LBLTDegree;

    @FXML
    private Label LBLTDeptID;

    @FXML
    private Label LBLTGender;

    @FXML
    private Label LBLTID;

    @FXML
    private Label LBLTName;

    @FXML
    private Label LBLTSpeciality;

    @FXML
    private TextField TFDAge;

    @FXML
    private TextField TFDDeptID;

    @FXML
    private TextField TFDDuty;

    @FXML
    private TextField TFDGender;

    @FXML
    private TextField TFDID;

    @FXML
    private TextField TFDName;

    @FXML
    private TextField TFDWorkload;

    @FXML
    private TextField TFDescription;

    @FXML
    private TextField TFID;

    @FXML
    private TextField TFSDeptID;

    @FXML
    private TextField TFSDuty;

    @FXML
    private TextField TFSGender;

    @FXML
    private TextField TFSID;

    @FXML
    private TextField TFSName;

    @FXML
    private TextField TFSTCourse;

    @FXML
    private TextField TFSTDeptID;

    @FXML
    private TextField TFSTGender;

    @FXML
    private TextField TFSTID;

    @FXML
    private TextField TFSTName;

    @FXML
    private TextField TFSWorkload;

    @FXML
    private TextField TFTAge;

    @FXML
    private TextField TFTDegree;

    @FXML
    private TextField TFTDeptID;

    @FXML
    private TextField TFTGender;

    @FXML
    private TextField TFTID;

    @FXML
    private TextField TFTSpeciality;

    @FXML
    private TextField TITName;

    @FXML
    void DDelete(ActionEvent event) {

    }

    @FXML
    void DLoad(ActionEvent event) {

    }

    @FXML
    void DSave(ActionEvent event) {

    }

    @FXML
    void DSearch(ActionEvent event) {

    }

    @FXML
    void DUpdate(ActionEvent event) {

    }

    @FXML
    void DeptDelete(ActionEvent event) {

    }

    @FXML
    void DeptLoad(ActionEvent event) {

    }

    @FXML
    void DeptSave(ActionEvent event) {

    }

    @FXML
    void DeptSearch(ActionEvent event) {

    }

    @FXML
    void DeptUpdate(ActionEvent event) {

    }

    @FXML
    void SDelete(ActionEvent event) {

    }

    @FXML
    void SLoad(ActionEvent event) {

    }

    @FXML
    void SSave(ActionEvent event) {

    }

    @FXML
    void SSearch(ActionEvent event) {

    }

    @FXML
    void STDelete(ActionEvent event) {

    }

    @FXML
    void STLoad(ActionEvent event) {

    }

    @FXML
    void STSave(ActionEvent event) {

    }

    @FXML
    void STSearch(ActionEvent event) {

    }

    @FXML
    void STUpdate(ActionEvent event) {

    }

    @FXML
    void SUpdate(ActionEvent event) {

    }

    @FXML
    void TDelete(ActionEvent event) {

    }

    @FXML
    void TLoad(ActionEvent event) {

    }

    @FXML
    void TSave(ActionEvent event) {

    }

    @FXML
    void TSearch(ActionEvent event) {

    }

    @FXML
    void TUpdate(ActionEvent event) {

    }

}
